import React from 'react';
import { Link } from 'react-router-dom';
import {
  Zap,
  Shield,
  Users,
  ArrowRight,
  CheckCircle2,
  Scale,
  MessageSquare,
  FileText,
  Gavel
} from 'lucide-react';
import { Logo } from '../components/Logo';

const LandingPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-secondary-50 font-sans selection:bg-primary-100 selection:text-primary-900">
      {/* Navigation */}
      <nav className="fixed w-full bg-white/80 backdrop-blur-xl border-b border-secondary-100 z-50 transition-all duration-300">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <div className="flex items-center gap-3">
              <Logo className="h-10 w-10" />
              <span className="text-xl font-bold text-neutral-900 tracking-tight">QuikCort</span>
            </div>
            <div className="hidden md:flex items-center space-x-8">
              <a href="#features" className="text-sm font-medium text-secondary-600 hover:text-neutral-900 transition-colors">Features</a>
              <a href="#how-it-works" className="text-sm font-medium text-secondary-600 hover:text-neutral-900 transition-colors">How it Works</a>
              <div className="flex items-center space-x-4 ml-4">
                <Link
                  to="/login"
                  className="text-sm font-medium text-neutral-900 hover:text-primary-600 transition-colors"
                >
                  Sign In
                </Link>
                <Link
                  to="/register"
                  className="bg-neutral-900 hover:bg-neutral-800 text-white px-5 py-2.5 rounded-full text-sm font-medium transition-all shadow-lg shadow-neutral-900/20 hover:shadow-neutral-900/30 hover:-translate-y-0.5"
                >
                  Get Started
                </Link>
              </div>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="relative pt-32 pb-20 lg:pt-48 lg:pb-32 overflow-hidden">
        {/* Abstract Background Elements */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full -z-10">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-primary-200/30 rounded-full blur-3xl mix-blend-multiply animate-blob"></div>
          <div className="absolute top-0 right-1/4 w-96 h-96 bg-purple-200/30 rounded-full blur-3xl mix-blend-multiply animate-blob animation-delay-2000"></div>
          <div className="absolute -bottom-32 left-1/3 w-96 h-96 bg-pink-200/30 rounded-full blur-3xl mix-blend-multiply animate-blob animation-delay-4000"></div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-secondary-200 shadow-sm mb-8 animate-fade-in-up">
            <span className="flex h-2 w-2 rounded-full bg-green-500 animate-pulse"></span>
            <span className="text-sm font-medium text-secondary-600">AI-Powered Mediation 2.0 is here</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-bold text-neutral-900 mb-8 tracking-tight leading-[1.1] max-w-5xl mx-auto">
            Resolve Disputes with <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-600 to-purple-600">Unbiased Intelligence</span>
          </h1>

          <p className="text-xl md:text-2xl text-secondary-600 mb-12 max-w-2xl mx-auto leading-relaxed">
            The modern way to settle conflicts. Fast, fair, and legally sound verdicts generated by advanced AI in minutes, not months.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              to="/register"
              className="group bg-neutral-900 hover:bg-neutral-800 text-white px-8 py-4 rounded-full text-lg font-semibold inline-flex items-center transition-all shadow-xl shadow-neutral-900/20 hover:shadow-neutral-900/30 hover:-translate-y-1"
            >
              Start Free Mediation
              <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link
              to="/login"
              className="group bg-white border border-secondary-200 hover:border-secondary-300 text-neutral-900 px-8 py-4 rounded-full text-lg font-medium transition-all shadow-sm hover:shadow-md"
            >
              View Demo Case
            </Link>
          </div>

          {/* Trust Indicators */}
          <div className="mt-16 pt-8 border-t border-secondary-200/60 max-w-4xl mx-auto">
            <p className="text-sm font-medium text-secondary-400 mb-6 uppercase tracking-wider">Trusted by individuals and businesses for</p>
            <div className="flex flex-wrap justify-center gap-8 md:gap-16 opacity-60 grayscale hover:grayscale-0 transition-all duration-500">
              {/* Placeholders for "Trusted By" logos - using text for now but styled like logos */}
              <span className="text-xl font-bold text-secondary-400">Freelance disputes</span>
              <span className="text-xl font-bold text-secondary-400">Property claims</span>
              <span className="text-xl font-bold text-secondary-400">Contract issues</span>
              <span className="text-xl font-bold text-secondary-400">E-commerce</span>
            </div>
          </div>
        </div>
      </div>

      {/* Bento Grid Features Section */}
      <div id="features" className="py-24 bg-white relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-neutral-900 mb-4 tracking-tight">
              Everything you need to reach a resolution
            </h2>
            <p className="text-xl text-secondary-600 max-w-2xl mx-auto">
              A complete platform designed to de-escalate conflict and provide clear, actionable outcomes.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[300px]">
            {/* Large Card - Speed */}
            <div className="md:col-span-2 row-span-1 bg-secondary-50 rounded-3xl p-8 border border-secondary-100 relative overflow-hidden group hover:shadow-lg transition-all duration-300">
              <div className="absolute top-0 right-0 w-64 h-64 bg-primary-100 rounded-full blur-3xl -mr-16 -mt-16 opacity-50 group-hover:opacity-70 transition-opacity"></div>
              <div className="relative z-10 h-full flex flex-col justify-between">
                <div>
                  <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-6">
                    <Zap className="h-6 w-6 text-primary-600" />
                  </div>
                  <h3 className="text-2xl font-bold text-neutral-900 mb-2">Lightning Fast Resolution</h3>
                  <p className="text-secondary-600 text-lg max-w-md">
                    Skip the months of waiting. Our AI analyzes evidence and statements instantly to provide a preliminary verdict in minutes.
                  </p>
                </div>
                <div className="flex items-center gap-4 text-sm font-medium text-primary-700">
                  <span className="bg-white px-3 py-1 rounded-full shadow-sm">Avg. time: 5 mins</span>
                  <span className="bg-white px-3 py-1 rounded-full shadow-sm">24/7 Availability</span>
                </div>
              </div>
            </div>

            {/* Tall Card - Neutrality */}
            <div className="md:col-span-1 row-span-2 bg-neutral-900 rounded-3xl p-8 relative overflow-hidden group">
              <div className="absolute inset-0 bg-gradient-to-b from-neutral-800 to-neutral-900"></div>
              <div className="relative z-10 h-full flex flex-col">
                <div className="w-12 h-12 bg-neutral-800 rounded-2xl flex items-center justify-center mb-6 border border-neutral-700">
                  <Scale className="h-6 w-6 text-primary-400" />
                </div>
                <h3 className="text-2xl font-bold text-white mb-4">Unbiased &<br />Impartial</h3>
                <p className="text-secondary-400 mb-8">
                  Eliminate human bias. Our algorithms are trained to focus purely on facts, evidence, and established principles of fairness.
                </p>

                {/* Visual representation of balance */}
                <div className="mt-auto relative h-48 w-full bg-neutral-800/50 rounded-xl border border-neutral-700 p-4 flex items-center justify-center">
                  <div className="absolute w-32 h-1 bg-neutral-600 rounded-full"></div>
                  <div className="absolute w-1 h-16 bg-neutral-600 rounded-full bottom-1/2"></div>
                  <div className="absolute left-8 bottom-1/2 translate-y-4 w-12 h-12 rounded-full border-2 border-primary-500/30 flex items-center justify-center">
                    <div className="w-8 h-8 bg-primary-500 rounded-full opacity-20 animate-pulse"></div>
                  </div>
                  <div className="absolute right-8 bottom-1/2 translate-y-4 w-12 h-12 rounded-full border-2 border-purple-500/30 flex items-center justify-center">
                    <div className="w-8 h-8 bg-purple-500 rounded-full opacity-20 animate-pulse animation-delay-1000"></div>
                  </div>
                </div>
              </div>
            </div>

            {/* Medium Card - Evidence */}
            <div className="md:col-span-1 bg-white rounded-3xl p-8 border border-secondary-200 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="w-12 h-12 bg-purple-50 rounded-2xl flex items-center justify-center mb-6">
                <FileText className="h-6 w-6 text-purple-600" />
              </div>
              <h3 className="text-xl font-bold text-neutral-900 mb-2">Evidence Based</h3>
              <p className="text-secondary-600">
                Upload documents, photos, and chat logs. The AI considers all submitted proof.
              </p>
            </div>

            {/* Medium Card - User Centric */}
            <div className="md:col-span-1 bg-white rounded-3xl p-8 border border-secondary-200 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="w-12 h-12 bg-green-50 rounded-2xl flex items-center justify-center mb-6">
                <Users className="h-6 w-6 text-green-600" />
              </div>
              <h3 className="text-xl font-bold text-neutral-900 mb-2">Collaborative</h3>
              <p className="text-secondary-600">
                Invite the opposing party easily via email to join the mediation process.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* How It Works - Step Strip */}
      <div id="how-it-works" className="py-24 bg-secondary-50 border-y border-secondary-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-12">
            <div className="md:w-1/3">
              <h2 className="text-3xl font-bold text-neutral-900 mb-4 tracking-tight">Simple 3-Step Process</h2>
              <p className="text-secondary-600 text-lg">
                We've stripped away the complexity of legal proceedings to get you straight to a resolution.
              </p>
              <div className="mt-8">
                <Link to="/register" className="text-primary-600 font-semibold hover:text-primary-700 flex items-center">
                  Start your case now <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </div>
            </div>

            <div className="md:w-2/3 grid grid-cols-1 sm:grid-cols-3 gap-8">
              {[
                { icon: MessageSquare, title: "1. Create Case", desc: "Describe the dispute and invite the other party." },
                { icon: FileText, title: "2. Submit Evidence", desc: "Both sides upload their statements and proof." },
                { icon: Gavel, title: "3. Get Verdict", desc: "Receive a formal resolution document." }
              ].map((step, i) => (
                <div key={i} className="relative pl-4 border-l-2 border-secondary-200 hover:border-primary-500 transition-colors duration-300">
                  <step.icon className="h-6 w-6 text-secondary-400 mb-3" />
                  <h3 className="text-lg font-bold text-neutral-900 mb-1">{step.title}</h3>
                  <p className="text-sm text-secondary-600">{step.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="relative py-24 bg-neutral-900 overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop')] bg-cover bg-center opacity-10 mix-blend-overlay"></div>
        <div className="absolute inset-0 bg-gradient-to-t from-neutral-900 via-transparent to-transparent"></div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6 tracking-tight">
            Ready to find common ground?
          </h2>
          <p className="text-xl text-secondary-300 mb-10 max-w-2xl mx-auto">
            Join thousands of users who have successfully resolved their conflicts without the stress of court.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/register"
              className="bg-primary-600 hover:bg-primary-500 text-white px-10 py-4 rounded-full text-lg font-semibold inline-flex items-center transition-all shadow-lg shadow-primary-900/50 hover:scale-105"
            >
              Get Started for Free
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-white border-t border-secondary-200 pt-16 pb-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
            <div className="col-span-1 md:col-span-1">
              <div className="flex items-center gap-2 mb-4">
                <Logo className="h-8 w-8" />
                <span className="text-xl font-bold text-neutral-900">QuikCort</span>
              </div>
              <p className="text-secondary-500 text-sm leading-relaxed">
                The future of dispute resolution. Fast, fair, and accessible to everyone.
              </p>
            </div>

            <div>
              <h4 className="font-bold text-neutral-900 mb-4">Platform</h4>
              <ul className="space-y-2 text-sm text-secondary-600">
                <li><a href="#" className="hover:text-primary-600">How it Works</a></li>
                <li><a href="#" className="hover:text-primary-600">Pricing</a></li>
                <li><a href="#" className="hover:text-primary-600">For Business</a></li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-neutral-900 mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-secondary-600">
                <li><a href="#" className="hover:text-primary-600">About Us</a></li>
                <li><a href="#" className="hover:text-primary-600">Careers</a></li>
                <li><a href="#" className="hover:text-primary-600">Contact</a></li>
              </ul>
            </div>

            <div>
              <h4 className="font-bold text-neutral-900 mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-secondary-600">
                <li><a href="#" className="hover:text-primary-600">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-primary-600">Terms of Service</a></li>
              </ul>
            </div>
          </div>

          <div className="border-t border-secondary-100 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm text-secondary-400">
              © {new Date().getFullYear()} QuikCort. All rights reserved.
            </p>
            <div className="flex gap-6">
              {/* Social placeholders */}
              <div className="w-5 h-5 bg-secondary-200 rounded-full"></div>
              <div className="w-5 h-5 bg-secondary-200 rounded-full"></div>
              <div className="w-5 h-5 bg-secondary-200 rounded-full"></div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
